name: Dockerhub Continuous Deployment

on:
  push:
    branches: [ dockercd ]

jobs:
  push_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: package
        working-directory: demo/
        run: mvn package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: ls demo/target
      - run: ls

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/dockercd:latest demo

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/dockercd:latest
