name: Test Java

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Run tests
        working-directory: Test/miapp
        run: mvn test
